# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=b'client_files', verbose_name=b'archivo')),
                ('file_name', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'Nombre del documento')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name=b'nombre')),
                ('description', models.CharField(max_length=200, verbose_name=b'descripci\xc3\xb3n')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=45, verbose_name=b'direcci\xc3\xb3n')),
                ('phone', models.CharField(blank=True, max_length=45, null=True, verbose_name=b'n\xc3\xbamero de telefono')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name=b'fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'M'), (b'F', b'F')], max_length=1, null=True, verbose_name=b'g\xc3\xa9nero')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=b'pofile_pictures', verbose_name=b'imagen de perfil')),
                ('observations', models.TextField(blank=True, null=True, verbose_name=b'observaciones')),
                ('curp', models.CharField(blank=True, max_length=45, null=True, verbose_name=b'CURP')),
                ('rfc', models.CharField(blank=True, max_length=45, null=True, verbose_name=b'RFC')),
                ('ib_key', models.CharField(blank=True, max_length=45, null=True, verbose_name=b'clave inerbancaria')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'usuario')),
                ('destination_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.Bank', verbose_name=b'banco de destino')),
            ],
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.DocumentType', verbose_name=b'Documento'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name=b'Perfil'),
        ),
    ]
