# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=145, verbose_name=b'Direcci\xc3\xb3n')),
                ('zipcode', models.CharField(blank=True, max_length=8, null=True, verbose_name=b'C\xc3\xb3digo postal')),
                ('latitude', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'Latitud')),
                ('longitude', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'Longitud')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.City', verbose_name=b'Ciudad')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='dream_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_dreamworker_profile', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.DocumentType', verbose_name=b'Documento'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'descripci\xc3\xb3n'),
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name=b'Perfil de usuario'),
        ),
    ]
