# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170226_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_dream_worker',
            field=models.BooleanField(default=0, verbose_name=b'es DreamWorker'),
        ),
    ]
