# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name=b'nombre')),
                ('description', models.CharField(max_length=200, verbose_name=b'descripci\xc3\xb3n')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_persons', models.PositiveIntegerField(default=1, verbose_name=b'viajantes')),
                ('written_destination', models.CharField(max_length=45, verbose_name=b'destino')),
                ('details', models.TextField(verbose_name=b'detalles')),
                ('init_date', models.DateTimeField(blank=True, null=True, verbose_name=b'fecha inicial')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name=b'fecha Final')),
                ('request_date', models.DateTimeField(blank=True, null=True, verbose_name=b'fecha Final')),
                ('agency_price', models.PositiveIntegerField(verbose_name=b'precio de la agencia')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'email')),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name=b'cantidad')),
                ('payment_file', models.FileField(blank=True, null=True, upload_to=b'', verbose_name=b'archivo')),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name=b'fecha de registro')),
            ],
        ),
    ]
