# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20170226_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to=b'galleries'),
        ),
    ]
