# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_photograph'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='circle_photograph',
            field=models.ImageField(blank=True, null=True, upload_to=b'galleries'),
        ),
    ]
